### ISSUE TITLE
Heart Rate Monitor checklist

### ISSUE THREAD

**Issue by shinkuri** [shinkuri/biomon#2]
- [x] implement backup command
- [x] implement RLE compression for heartrate data
- [x] update read ops to work with RLE
- [x] add code to read hrm over ble
- [x] persist ble setup params for easy restart

**Comment by shinkuri** [comment]
Ini file is read on app startup and very naively written back to on shutdown. This causes any manual edits to the ini file to during runtime to be lost. Fine by me. Maybe I'll add a reload at some point.

Further steps from here are turning ble_hrp.rs into a Collector with a common trait, putting it on another thread, and replacing the current command with start/stop ones.
